### ISSUE TITLE
Manual review: updating a ready review does not update submission score.

### ISSUE THREAD

**Issue by 0xf8f8ff** [quickfeed/quickfeed#930] opened 2022-11-21 15:28 UTC
There is currently an issue for manual review submissions when the submission score updates back to the old score when re-grading a ready review and then changing the approved status of a submission. 

How to reproduce:

1. Create a review with a score of `A`, set it to `Ready`, and click any of the `Approve`/`Revision`/`Reject`. Everything is working as intended here, both `Review` and `Submission` will have `Score: A` in the database.
2. Open the review, and change some criteria marks so that the review has a new score of `B`. At this point, both `Review` and `Submission` have `Score: B` in the database.
3. Now change the `Approved` status of the submission. As a result, the `Review` will have `Score: B`, but the `Submission` will be updated back to `Score: A`.

Looks like the reason for this is that the front end sends the old `Score` value in a request to the `UpdateSubmissionRequest`.

**Comment by JosteinLindhom** [comment] 2023-05-05 11:14
Unable to reproduce. Fairly certain this was resolved in #943.

**Comment by meling** [comment] 2023-05-05 17:06
Closing as resolved.

**Closed by meling** 2023-05-05 17:06 UTC
Labels: bug
